# Generated by Django 3.2.25 on 2024-04-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=150, verbose_name='Название')),
                ('Description', models.TextField(verbose_name='Статья')),
                ('Quantity', models.CharField(max_length=150, verbose_name='Количество')),
                ('Image', models.FileField(upload_to='', verbose_name='Изображение')),
                ('Price', models.CharField(max_length=250, verbose_name='Цена')),
            ],
        ),
    ]
