# Generated by Django 3.2.25 on 2024-04-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.FileField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
