# Generated by Django 3.2.25 on 2024-05-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artical', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Лист продуктов', 'verbose_name_plural': 'Лист продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='Categories',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Cartproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US', models.CharField(max_length=150, verbose_name='ID Пользователя')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artical.product')),
            ],
        ),
    ]
