# Generated by Django 3.2.25 on 2024-05-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artical', '0003_auto_20240515_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Category', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artical.category'),
        ),
    ]
