# Generated by Django 3.2.25 on 2024-05-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artical', '0004_auto_20240516_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproducts',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
