# Generated by Django 3.2.25 on 2024-05-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artical', '0005_auto_20240522_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=150, verbose_name='ID Пользователя')),
                ('Order_number', models.CharField(max_length=150, verbose_name='Номер заказ')),
                ('Products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artical.product')),
            ],
        ),
    ]
